# ==============================================================
# Makefile for ABD/HOL
# ==============================================================

default: theory

clean:
	cd ACL; make clean; cd ..
	cd ssms; make clean; cd ..
	cd OMNILevel; make clean; cd ..
	cd topLevel; make clean; cd ..
	cd subLevel; make clean; cd ..
	cd HOLReportsOMNI; make clean; cd ..

theory:
	cd ACL; make; cd ..
	cd ssms; make; cd ..
	cd OMNILevel; make; cd ..
	cd topLevel; make; cd ..
	cd subLevel; make; cd ..
	cd HOLReportsOMNI; make; cd ..
