# ==============================================================
# Makefile for ABD/HOL
# ==============================================================

default: theory

clean:
	cd ConductORP; make clean; cd ..
	cd ConductPB; make clean; cd ..
	cd MoveToORP; make clean; cd ..
	cd MoveToPB; make clean; cd ..
	cd PlanPB; make clean; cd ..

theory:
	cd ConductORP; make; cd ..
	cd ConductPB; make; cd ..
	cd MoveToORP; make; cd ..
	cd MoveToPB; make; cd ..
	cd PlanPB; make; cd ..
