# ===================================================
# Makefile for HLSM Exericses Theory 
# ===================================================

default: theory

clean:
	Holmake cleanAll
	cd HOLReports;make clean

theory:
	Holmake cleanAll;Holmake;cd HOLReports;make clean;make
