# ===================================================
# Makefile for HLSM Examples Theory 
# ===================================================

default: theory

clean:
	cd ssm;make clean

theory:
	cd ssm;make
