# ===================================================
# Makefile for HLSM Examples Theory 
# ===================================================

default: theory

clean:
	cd SM0;make clean

theory:
	cd SM0;make
